# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ 
    "xhci_pci"
    "ahci" "nvme" "usbhid" "usb_storage"
    "sd_mod" 
    ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/57583232-d300-40d8-ae04-3ae510697a13";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2d8b5a20-2780-43b6-a0f8-e26bd36d19e6".device = "/dev/disk/by-uuid/2d8b5a20-2780-43b6-a0f8-e26bd36d19e6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/739A-7657";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8c497dfb-c2ae-46d1-9314-305dddd50620"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
